config/routes.rb
Rails.application.routes.draw do
  default_url_options host: "localhost:3000"
  devise_for :users, controllers: {registrations: "registrations"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :home, only: :index
  resources :customers, only: :create
  resources :connect_sessions, only: :create
  resources :connections, only: [:index, :destroy] do
    put "refresh", on: :member
    put "reconnect", on: :member
    resources :accounts, only: :index do
      resources :transactions, only: :index
    end
  end

  namespace :admin do
    resources :connections, only: [:index, :show]
    resources :accounts, only: [:index, :show]
    resources :transactions, only: [:index, :show]
  end

  namespace :api do
    namespace :v1 do
      resources :connections, only: :create
    end
  end
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :customer

  has_many :accounts
end

app/controllers/admin/connections_controller.rb
module Admin
  class ConnectionsController < ApplicationController
    def index
      @connections = Connection.all
    end

    def show
      @connection = Connection.preload(:accounts).find(params[:id])
    end
  end
end

app/controllers/api/v1/connections_controller.rb
module Api
  module V1
    class ConnectionsController < BaseController
      def create
        data = params["data"]
        create_connection(data["customer_id"], data["connection_id"])
      end

      private

      def create_connection(customer_id, connection_id)
        customer = Customer.find_by(remote_id: customer_id)
        connection = Connection.find_by(remote_id: connection_id)
        Connection.create(customer: customer, remote_id: connection_id) unless connection
      end
    end
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  def index
    customer = current_user.customer
    @connections = customer.connections
    if params[:fetch_remote]
      response = SaltEdge::ConnectionGateway.new.get_list(customer_id: customer.remote_id, from_id: @connections.last&.remote_id)
      if response.is_a?(Array)
        current_ids = @connections.map(&:remote_id)
        response.filter { current_ids.exclude?(_1[:id]) }.each do |connection|
          @connections << Connection.create(
            customer: customer,
            remote_id: connection[:id],
            country_code: connection[:country_code],
            last_success_at: connection[:last_success_at],
            next_refresh_possible_at: connection[:next_refresh_possible_at],
            provider_id: connection[:provider_id],
            provider_code: connection[:provider_code],
            provider_name: connection[:provider_name],
            status: connection[:status],
            response: connection
          )
        end
      end
    end
  end

  def refresh
    connection = current_user.customer.connections.find(params[:id])
    if connection
      response = SaltEdge::ConnectionGateway.new.refresh(connection_id: connection.remote_id)
      if response.has_key?(:error)
        flash[:alert] = response[:message]
      else
        connection.update!(
          country_code: response[:country_code],
          last_success_at: response[:last_success_at],
          next_refresh_possible_at: response[:next_refresh_possible_at],
          provider_id: response[:provider_id],
          provider_code: response[:provider_code],
          provider_name: response[:provider_name],
          status: response[:status],
          response: response
        )
      end
    end
    redirect_to connections_path
  end

  def reconnect
    connection = current_user.customer.connections.find(params[:id])
    if connection
      response = SaltEdge::ConnectionGateway.new.reconnect(connection_id: connection.remote_id, user: current_user)
      if response.has_key?(:error)
        flash[:alert] = response[:message]
      else
        connection.update!(
          country_code: response[:country_code],
          last_success_at: response[:last_success_at],
          next_refresh_possible_at: response[:next_refresh_possible_at],
          provider_id: response[:provider_id],
          provider_code: response[:provider_code],
          provider_name: response[:provider_name],
          status: response[:status],
          response: response
        )
      end
    end
    redirect_to connections_path
  end

  def destroy
    connection = current_user.customer.connections.find(params[:id])
    if connection
      response = SaltEdge::ConnectionGateway.new.destroy(connection_id: connection.remote_id)
      if response.has_key?(:error)
        flash[:alert] = response[:message]
      else
        connection.update!(removed: true)
      end
    end
    redirect_to connections_path
  end
end

app/views/connections/_entity.html.erb
<div class="col-sm-4 mt-4">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= connection.provider_name %></h5>
      <% if connection.removed %>
        <h6 class="card-subtitle mb-2 text-muted">Removed</h6>
      <% else %>
        <h6 class="card-subtitle mb-2 text-muted">Code: <%= connection.provider_code %></h6>
        <h6 class="card-subtitle mb-2 text-muted">Id: <%= connection.remote_id %></h6>
        <h6 class="card-subtitle mb-2 text-muted">Status: <%= connection.status %></h6>
        <%= link_to("Accounts", connection_accounts_path(connection_id: connection.id), class: "card-link") %>
        <%= link_to("Accounts Remote", connection_accounts_path(connection_id: connection.id, fetch_remote: true), class: "card-link") %>
        <p class="card-text">Next refresh possible at: <%= connection.next_refresh_possible_at&.strftime("%m/%d/%Y at %I:%M%p") %></p>
        <% if connection.next_refresh_possible_at && Time.current > connection.next_refresh_possible_at %>
          <%= button_to("Refresh", refresh_connection_path(connection), method: :put, class: "btn btn-primary") %>
        <% end %>
        <%= button_to("Reconnect", reconnect_connection_path(connection), method: :put, class: "btn btn-success mt-2") %>
        <%= button_to("Remove", connection_path(connection), method: :delete, class: "btn btn-danger mt-2") %>
      <% end %>
    </div>
  </div>
</div>

app/views/connections/index.html.erb
<h1>Connections</h1>

<% @connections.each do |connection| %>
  <%= render "entity", connection: connection %>
<% end %>