config/routes.rb
Rails.application.routes.draw do
  default_url_options host: "localhost:3000"
  devise_for :users, controllers: {registrations: "registrations"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :home, only: :index
  resources :customers, only: :create
  resources :connect_sessions, only: :create
  resources :connections, only: [:index, :destroy] do
    put "refresh", on: :member
    put "reconnect", on: :member
    resources :accounts, only: :index do
      resources :transactions, only: :index
    end
  end

  namespace :admin do
    resources :connections, only: [:index, :show]
    resources :accounts, only: [:index, :show]
    resources :transactions, only: [:index, :show]
  end

  namespace :api do
    namespace :v1 do
      resources :connections, only: :create
    end
  end
end

app/controllers/admin/transactions_controller.rb
module Admin
  class TransactionsController < ApplicationController
    def index
      @transactions = Transaction.all
    end

    def show
      @transaction = Transaction.find(params[:id])
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    connection = current_user.customer.connections.find(params[:connection_id])
    @account = connection.accounts.find(params[:account_id])
    @transactions = @account.transactions
    if params[:fetch_remote]
      response = SaltEdge::TransactionGateway.new
        .get_list(connection_id: connection.remote_id, account_id: @account.remote_id, from_id: @transactions.last&.remote_id)
      if response.is_a?(Array)
        current_ids = @transactions.map(&:remote_id)
        response.filter { current_ids.exclude?(_1[:id]) }.each do |transaction|
          @transactions << Transaction.create(
            account: @account,
            remote_id: transaction[:id],
            duplicated: transaction[:duplicated],
            mode: transaction[:mode],
            status: transaction[:status],
            made_on: transaction[:made_on],
            currency_code: transaction[:currency_code],
            description: transaction[:description],
            category: transaction[:category]
          )
        end
      end
    end
  end
end

app/views/admin/transactions/index.html.erb
<h1>All Transactions</h1>

<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Duplicated</th>
    <th scope="col">Mode</th>
    <th scope="col">Status</th>
    <th scope="col">Made On</th>
    <th scope="col">Amount</th>
    <th scope="col">Currency</th>
    <th scope="col">Description</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @transactions.each do |transaction| %>
    <tr>
      <th scope="row"><%= transaction.id %></th>
      <td><%= transaction.duplicated %></td>
      <td><%= transaction.mode %></td>
      <td><%= transaction.status %></td>
      <td><%= transaction.made_on %></td>
      <td><%= transaction.amount %></td>
      <td><%= transaction.currency_code %></td>
      <td><%= transaction.description %></td>
      <td><%= link_to("Open", admin_transaction_path(transaction)) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/transactions/show.html.erb
<div class="col-sm-4 mt-4">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= @transaction.id %></h5>
      <h6 class="card-subtitle mb-2 text-muted">Duplicated: <%= @transaction.duplicated %></h6>
      <h6 class="card-subtitle mb-2 text-muted">Id: <%= @transaction.remote_id %></h6>
      <h6 class="card-subtitle mb-2 text-muted">Mode: <%= @transaction.mode %></h6>
      <h6 class="card-subtitle mb-2 text-muted">Status: <%= @transaction.status %></h6>
      <h6 class="card-subtitle mb-2 text-muted">Made on: <%= @transaction.made_on %></h6>
      <h6 class="card-subtitle mb-2 text-muted">Amount: <%= @transaction.amount %></h6>
      <h6 class="card-subtitle mb-2 text-muted">Currency: <%= @transaction.currency_code %></h6>
      <h6 class="card-subtitle mb-2 text-muted">Description: <%= @transaction.description %></h6>
      <h6 class="card-subtitle mb-2 text-muted">Category: <%= @transaction.category %></h6>
    </div>
  </div>
</div>